app/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import UsuarioDetailView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', UsuarioDetailView.as_view(template_name="base.html"), name="home"),  # MENU
    path('', include('register.urls')),
]

register/urls.py
from django.urls import path
from .views import Pf_DetailView, Pf_ListView, Pf_CreateView, Pf_UpdateView, Pf_DeleteView
from .views import Pj_DetailView, Pj_ListView, Pj_CreateView, Pj_UpdateView, Pj_DeleteView
from .views import Pf_Log_View, Pj_Log_View, Contacts_ListView


app_name = 'register'


urlpatterns = [
    # Pessoa
    path('pf/', Pf_ListView.as_view(), name='person_'),
    path('pf/0/adicionar/', Pf_CreateView.as_view(), name='person_add'),
    path('pf/<int:pk>/visualizar/', Pf_DetailView.as_view(), name='person_detail'),
    path('pf/<int:pk>/editar/', Pf_UpdateView.as_view(), name='person_change'),
    path('pf/<int:pk>/deletar/', Pf_DeleteView.as_view(), name='person_delete'),
    path('pf/<int:pk>/log/', Pf_Log_View.as_view(), name='person_log'),
    # Empresa
    path('pj/', Pj_ListView.as_view(), name='enterprise_'),
    path('pj/0/adicionar/', Pj_CreateView.as_view(), name='enterprise_add'),
    path('pj/<int:pk>/visualizar/', Pj_DetailView.as_view(), name='enterprise_detail'),
    path('pj/<int:pk>/editar/', Pj_UpdateView.as_view(), name='enterprise_edit'),
    path('pj/<int:pk>/deletar/', Pj_DeleteView.as_view(), name='enterprise_delete'),
    path('pj/<int:pk>/log/', Pj_Log_View.as_view(), name='enterprise_log'),
    # Utilitarios
    path('agenda/', Contacts_ListView.as_view(), name='contacts_'),
]

app/templates/base.html
<!doctype html>
{% load static %}
<html lang="pt-br">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %}{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.8/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-sRIl4kxILFvY47J16cr9ZwB07vP4J8+LH7qKQnuqkuIAvNWLzeN8tE5YBujZqJLB" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    
    <link rel="shortcut icon" href="#" type="image/x-icon">
    <meta http-equiv="Cache-Control" content="no-cache, no-store, must-revalidate" />
</head>

<body class="text-bg-light">
  <div class="bg-body-tertiary bg-gradient">
    <nav class="navbar navbar-expand-lg mb-5 container">
        <div class="container-fluid">
            <a class="navbar-brand" href="{% url 'home' %}">HOME</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'register:person_' %}">Pessoa Fisica</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'register:enterprise_' %}">Pessoa Juridica</a>
                  </li>

                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'register:contacts_' %}">Agenda</a>
                  </li>

                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'admin:index' %}">Django Admin</a>
                  </li>

                </ul>
                <ul class="navbar-nav gap-1 align-items-center">
                    <li class="nav-item">
                        {% include "theme.html" %}
                    </li>
                    {% if request.user.is_authenticated %}
                        <li class="nav-item">
                            <span class="nav-link">
                                <i class="bi bi-person-circle"></i> {{ request.user.username }}
                            </span>
                        </li>
                        <li class="nav-item">
                            <form method="post" action="{% url 'admin:logout' %}" class="d-inline">
                                {% csrf_token %}
                                <button type="submit" class="btn btn-danger">
                                    Sair
                                </button>
                            </form>
                        </li>
                    {% else %}
                        <li class="nav-item">
                            <a class="btn btn-primary"
                              href="{% url 'admin:login' %}?next={% url 'home' %}">
                                Login
                            </a>
                        </li>
                    {% endif %}
                </ul>

            </div>

        </div>
    </nav>
  </div>

    <section>
      {% include "alerts.html" %}
    </section>
    
    {% block content %}

      {% if not request.user.is_authenticated %}
        <div class="container d-flex justify-content-center">
          <div class="alert alert-info text-center w-75" role="alert">
            ⚠️ É necessário ter um usuário logado para efetuar cadastros pois o mesmo é salvo com o registro para log.
          </div>
        </div>
      {% endif  %}

      {% if request.user.is_authenticated %}
      <div class="container mt-3">
          <div class="row">

              <div class="col-12">
                  <h2>
                      <i class="bi bi-person-vcard me-1"></i>
                      Permissões
                  </h2>
                  <p class="lead">
                      Este usuário possui as seguintes permissões atribuídas via Django Admin:
                  </p>
              </div>

              <!-- Permissões diretas -->
              <div class="col-12 col-md-6 mb-3">
                  <label class="form-label fw-bold">Permissões do usuário:</label>

                  {% if user_permissions %}
                      <ul class="mb-0 ps-3">
                          {% for perm in user_permissions %}
                              <li>{{ perm.name }}</li>
                          {% endfor %}
                      </ul>
                  {% else %}
                      <div class="text-muted fst-italic">
                          Nenhuma permissão direta atribuída.
                      </div>
                  {% endif %}
              </div>

              <!-- Grupos -->
              <div class="col-12 col-md-6 mb-3">
                  <label class="form-label fw-bold">Grupos:</label>

                  <ul class="mb-0 ps-3">
                      {% if user.is_superuser %}
                          <li>
                            🛡️ Superusuário
                          </li>
                      {% endif %}

                      {% for group in groups %}
                          <li>{{ group.name }}</li>
                      {% empty %}
                          <li class="text-muted fst-italic">
                              Nenhum grupo associado.
                          </li>
                      {% endfor %}
                  </ul>
              </div>

          </div>
      </div>
      {% endif %}

    {% endblock %}

  <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.7/dist/js/bootstrap.min.js" integrity="sha384-7qAoOXltbVP82dhxHAUje59V5r2YsVfBafyUDxEdApLPmcdhBPg1DKg1ERo0BZlK" crossorigin="anonymous"></script>
</body>

</html>